version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_volume:/data
    ports:
      - 6379:6379

  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USE_TLS=false
      - BULL_PREFIX=bull
    depends_on:
      - redis

  adonis_api:
    container_name: api
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
      - 9229:9229
      - 8080:8080
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      - /home/node/app/node_modules
    command: dumb-init node ace serve --watch --encore-args="--host ${HOST} --port 8080 --public 127.0.0.1:8080"

volumes:
  postgres_volume:
  redis_volume:
